fragment ServiceParts on HealthHubService {
  emitDeclaration
  id
  info
  name
  price
  type
  description
  preparation
  result
  procedureFields {
    key
    label
    type
    position
    validations {
      min
      max
      required
      numbersOnly
      currentDate
    }
    values {
      key
      label
      data
    }
    data {
      unit
    }
  }
}

query service($id: ID!) {
  service(id: $id) {
    emitDeclaration
    id
    info
    name
    price
    type
    description
    preparation
    result
    procedureFields {
      key
      label
      type
      position
      validations {
        min
        max
        required
        numbersOnly
        currentDate
      }
      values {
        key
        label
        data
      }
      data {
        unit
      }
    }
  }
}

query services($page: Int, $size: Int, $type: HealthHubFieldType, $sort: String) {
  services(page: $page, size: $size, type: $type, sort: $sort) {
    content {
      ...ServiceParts
    }
    page
    totalPages
    totalElements
  }
}

mutation updateService($id: ID!, $service: HealthHubServiceInput!) {
  updateService(id: $id, service: $service) {
    ...ServiceParts
  }
}

mutation createService($service: HealthHubServiceInput!) {
  createService(service: $service) {
    ...ServiceParts
  }
}
